<?php

namespace RestBundle\Repository;

/**
 * UserVisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVisitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUniqueUsersByDateInterval($dateInterval)
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.visitDate >= :dateFrom')
            ->andWhere('u.visitDate <= :dateTo')
            ->setParameter('dateFrom', $dateInterval['from'])
            ->setParameter('dateTo', $dateInterval["to"])
            ->getQuery();

        return $query->getResult();
    }
}
