<?php

namespace RestBundle\Repository;

/**
 * UserVisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVisitRepository extends \Doctrine\ORM\EntityRepository
{
}
