<?php

namespace RestBundle\Repository;

/**
 * UserVisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVisitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersByDateInterval($from, $to)
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.visitDate >= :from')
            ->andWhere('u.visitDate <= :to')
            ->setParameter('from', $from)
            ->setParameter('to', $to)
            ->getQuery();

        return $query->getResult();
    }
}
